### ISSUE TITLE
二级导航空白

### ISSUE THREAD

**Issue by lnool** [lauset/vitepress-theme-vuetom#1]
![image](https://user-images.githubusercontent.com/34832876/171403982-ce63c93d-f14d-4564-b202-dca653ba525c.png)

![image](https://user-images.githubusercontent.com/34832876/171403919-8b047118-edb1-4916-8c96-7ec097fadee5.png)

复制过去，二级导航显示不出来

**Comment by lauset** [comment]
> ![image](https://user-images.githubusercontent.com/34832876/171403982-ce63c93d-f14d-4564-b202-dca653ba525c.png)
> 
> ![image](https://user-images.githubusercontent.com/34832876/171403919-8b047118-edb1-4916-8c96-7ec097fadee5.png)
> 
> 复制过去，二级导航显示不出来

我看了下问题哈，目前出现这种情况的原因是几天前更新过文档代码的缘故，该框架版本最新的是 1.0.8

1. 确保下.vitepress下config目录中的nav.ts等文件是最新的代码
2. 其次vitepress-theme-vuetom是1.0.8应该问题就不大了

希望可以帮到你😁，如果实在不行就尝试着运行一下该项目下最新的docs文档，再进行菜单的修改，不出意外是可以成功的
